# Generated by Django 2.2.28 on 2024-12-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('regular', 'Regular User'), ('guest', 'Guest')], default='regular', max_length=10),
        ),
    ]
