# Generated by Django 2.2.28 on 2024-12-24 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_fileshare_expire_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(upload_to=files.models.generate_encrypted_filename),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='permission',
            field=models.CharField(choices=[('view', 'View Only'), ('download', 'Download Allowed')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='share_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fileshare',
            unique_together={('file', 'shared_with')},
        ),
        migrations.RemoveField(
            model_name='fileshare',
            name='expire_days',
        ),
    ]
